"""Add Token table

Revision ID: 23987435967c
Revises: a60296db7140
Create Date: 2026-06-19 18:51:15.673715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23987435967c'
down_revision = 'a60296db7140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('set_code', sa.String(length=10), nullable=True),
    sa.Column('collector_number', sa.String(length=20), nullable=True),
    sa.Column('type_line', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
