"""add_price_to_art_card

Revision ID: 61b7aff49322
Revises: e52da809ed35
Create Date: 2026-06-20 00:58:07.532483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b7aff49322'
down_revision = 'e52da809ed35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art_card', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
