"""add value snapshot

Revision ID: 74fb71f25237
Revises: ee73becba52d
Create Date: 2026-06-19 17:07:28.358528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fb71f25237'
down_revision = 'ee73becba52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('is_foil')
        batch_op.drop_column('is_borderless')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_borderless', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_foil', sa.BOOLEAN(), nullable=True))

    op.drop_table('value_snapshot')
    # ### end Alembic commands ###
