"""Add mana metadata to Card

Revision ID: a60296db7140
Revises: ee6e3ad79443
Create Date: 2026-06-19 18:43:55.551823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60296db7140'
down_revision = 'ee6e3ad79443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana_cost', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cmc', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('type_line', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('colors')
        batch_op.drop_column('type_line')
        batch_op.drop_column('cmc')
        batch_op.drop_column('mana_cost')

    # ### end Alembic commands ###
