"""final setup

Revision ID: c340ac3b37fc
Revises: f23e0124ff2f
Create Date: 2026-06-19 15:07:39.455367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c340ac3b37fc'
down_revision = 'f23e0124ff2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
