"""Add ArtCard model

Revision ID: e52da809ed35
Revises: 23987435967c
Create Date: 2026-06-19 19:00:03.300576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52da809ed35'
down_revision = '23987435967c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('set_code', sa.String(length=10), nullable=True),
    sa.Column('collector_number', sa.String(length=20), nullable=True),
    sa.Column('type_line', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_card')
    # ### end Alembic commands ###
