"""add release notes

Revision ID: ee73becba52d
Revises: 12dae37ab825
Create Date: 2026-06-19 16:38:57.396118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee73becba52d'
down_revision = '12dae37ab825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=True),
    sa.Column('details', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('release_note')
    # ### end Alembic commands ###
